name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: npx install
          start: npx run build
  slackNotification:
    name: Cookies Consent Banner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cookies Consent Banner
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: ds-cookie-consent
